export const SECTION = {
	CLASSES_LIST: 0,
	ATTRIBUTES: 1,
	ATTRIBUTES_VALUES: 2,
	CLASSES_DESCRIPTION: 3,
	CLASSES_VALUES: 4,
	CHECK_COMPLETENESS_KNOWLEDGE: 5,
	DETERMINING_THE_CREDITWORTHINESS_CLASS: 6,
};

export const ATTRIBUTE_TYPE = {
	INT: 0,
	STRING: 1,
	BOOLEAN: 2,
	DOUBLE: 3,
};

export const ATTRIBUTE_TYPE_NAME = [
	"Целый",
	"Строчный",
	"Да/Нет",
	"С плавающей запятой"
];